### ISSUE TITLE
运行demo控制台报Main Thread Checker: UI API called on a background thread: -[UIView layer]

### ISSUE THREAD

**Issue by zpz5789** [polyv/polyv-ios-vod-sdk#1]
调用栈显示
4   PLPolyvVodPlayerDemo                0x00000001032d5c82 -[IJKSDLGLView displayInternal:] + 64
5   PLPolyvVodPlayerDemo                0x00000001032d5bf9 -[IJKSDLGLView display:] + 181
6   PLPolyvVodPlayerDemo                0x00000001032e5c9a vout_display_overlay + 85
7   PLPolyvVodPlayerDemo                0x00000001032d0b44 video_display2 + 384
8   PLPolyvVodPlayerDemo                0x00000001032ce956 video_refresh_thread + 2388
9   PLPolyvVodPlayerDemo                0x00000001032d3017 SDL_RunThread + 34
10  libsystem_pthread.dylib             0x000000010ad8193b _pthread_body + 180
11  libsystem_pthread.dylib             0x000000010ad81887 _pthread_body + 0
12  libsystem_pthread.dylib             0x000000010ad8108d thread_start + 13
2018-03-29 19:59:22.976005+0800 PLPolyvVodPlayerDemo[15679:1360270] [reports] Main Thread Checker: UI API called on a background thread: -[UIView layer]

定位到这行 -[IJKSDLGLView displayInternal:]  
这个有什么办法解决不，对使用sdk会不会有很大影响？

**Comment by bqlin** [comment]
经测试不影响 SDK 逻辑。
<https://github.com/Bilibili/ijkplayer/issues/3592>
