### ISSUE TITLE
gestureCallback

### ISSUE THREAD

**Issue by GridTT** [polyv/polyv-ios-vod-sdk#12]
播放状态的回调能走，这个手势的回调一直不走是怎么回事
player.gestureCallback = ^(PLVVodPlayerViewController *player, UIGestureRecognizer *recognizer, PLVVodGestureType gestureType) {}

**Comment by baymaxbowen** [comment]
猜测可能的解决办法，设置皮肤的背景为透明，就可以走通这个回调了

强烈吐槽PLV这么垃圾的设计机制

**Comment by dengjunlun** [comment]
这是因为block是一对一的，此block回调已经在PLVVodSkinPlayerController设置了。
建议您先了解一下block的原理和使用方法，祝您生活愉快
