### ISSUE TITLE
如果项目默认的是竖屏，如何指定单一的页面支持横竖屏

### ISSUE THREAD

**Issue by wxzwork** [polyv/polyv-ios-vod-sdk#15]
请问一下，目前demo中给的示例是必须开启横竖屏支持，但是实际项目中很多页面都是竖屏，只有播放页面才需要横竖屏，如何做到只在播放页面支持横竖屏播放

**Comment by lien006** [comment]
1 )实现AppDelegate 中supportedInterfaceOrientationsForWindow 代理方法
-(NSUInteger)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
    if (__allowRotation == YES) {
        return UIInterfaceOrientationMaskAllButUpsideDown;
    }
    return UIInterfaceOrientationMaskPortrait;
}
2）AppDelegate 中添加属性 __allowRotation，在需要横竖屏的页面中设置__allowRotation 为YES
