### ISSUE TITLE
iphone X横屏播放锁屏后，解锁成功无法上滑屏幕

### ISSUE THREAD

**Issue by zxCindy** [polyv/polyv-ios-vod-sdk#17]
在iPhone X上开启系统的竖屏锁定，然后横屏播放视频，手动锁屏后再解锁则无法上滑屏幕打开手机，请问是什么原因导致的呢，试了一下demo，也存在这个问题，望予以解答，感谢。

**Comment by dengjunlun** [comment]
目前这个问题在新版本的demo上已经解决了，您可以更新版本试试
