### ISSUE TITLE
cocoaPods 加了这些库,pod install以后就出现了如下的错误,项目也无法正常运行

### ISSUE THREAD

**Issue by weiwei1991** [polyv/polyv-ios-vod-sdk#20]
请尽快帮忙解决
<img width="653" alt="屏幕快照 2019-07-30 15 09 11" src="https://user-images.githubusercontent.com/7012340/62108302-54658780-b2dc-11e9-8be7-d1f1e2e93154.png">
<img width="923" alt="屏幕快照 2019-07-30 15 09 40" src="https://user-images.githubusercontent.com/7012340/62108304-54fe1e00-b2dc-11e9-998d-4b31d79a4409.png">

**Comment by weiwei1991** [comment]
Xcode版本是10.1

**Comment by xieyunjia** [comment]
请问是出现了什么错误？

**Comment by xieyunjia** [comment]
请问您的项目里面是集成了支付宝的SDK吗？从错误日志看，是我们SDK跟支付宝的SDK冲突了呢。您可以直接去支付宝的官网，获取一个不包含UTDID的SDK。

**Comment by weiwei1991** [comment]
这样不会影响我们项目的支付吧？

**Comment by weiwei1991** [comment]
更换了支付宝不包含UTDID的SDK,又出现了如下错误，请问该如何解决？
<img width="988" alt="屏幕快照 2019-07-30 17 34 39" src="https://user-images.githubusercontent.com/7012340/62118541-6bae7000-b2f0-11e9-9031-593677db0cb2.png">
<img width="988" alt="屏幕快照 2019-07-30 17 34 39" src="https://user-images.githubusercontent.com/7012340/62118543-6cdf9d00-b2f0-11e9-927a-c9281f4678ce.png">

**Comment by xieyunjia** [comment]
放心，我们的SDK里面已经包含了支付宝的UTDID.framework，所以使用支付宝提供的不包含 UTDID 的 SDK 包不影响支付功能的。

**Comment by xieyunjia** [comment]
我看你的错误日志，是 WCDB 这个库出现问题，可以加下你 qq 吗，方便沟通。

**Comment by weiwei1991** [comment]
1121721083  谢谢  这是我的Q
