### ISSUE TITLE
提示线程错误，UI操作未在主线程运行

### ISSUE THREAD

**Issue by jabbarwockeez** [polyv/polyv-ios-vod-sdk#22]
=================================================================
Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 16347, TID: 664485, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   HZClass                             0x0000000103a03b78 -[UTSelfStaticsManager getAppState] + 60
5   HZClass                             0x0000000103a03a74 -[UTSelfStaticsManager onEventForCrash] + 256
6   HZClass                             0x00000001039e2a34 __40-[UTMCSystemHook appDIdEnterBackground:]_block_invoke.51 + 196
7   libdispatch.dylib                   0x0000000107bdf6f4 _dispatch_call_block_and_release + 24
8   libdispatch.dylib                   0x0000000107be0c78 _dispatch_client_callout + 16
9   libdispatch.dylib                   0x0000000107be3ad4 _dispatch_queue_override_invoke + 876
10  libdispatch.dylib                   0x0000000107bf1dc8 _dispatch_root_queue_drain + 372
11  libdispatch.dylib                   0x0000000107bf27ac _dispatch_worker_thread2 + 156
12  libsystem_pthread.dylib             0x00000002040ee1b4 _pthread_wqthread + 464
13  libsystem_pthread.dylib             0x00000002040f0cd4 start_wqthread + 4
2019-09-20 08:15:26.604409+0800 HZClass[16347:664485] [reports] Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 16347, TID: 664485, Thread name: (none), Queue name: com.apple.root.default-qos, QoS: 0
Backtrace:
4   HZClass                             0x0000000103a03b78 -[UTSelfStaticsManager getAppState] + 60
5   HZClass                             0x0000000103a03a74 -[UTSelfStaticsManager onEventForCrash] + 256
6   HZClass                             0x00000001039e2a34 __40-[UTMCSystemHook appDIdEnterBackground:]_block_invoke.51 + 196
7   libdispatch.dylib                   0x0000000107bdf6f4 _dispatch_call_block_and_release + 24
8   libdispatch.dylib                   0x0000000107be0c78 _dispatch_client_callout + 16
9   libdispatch.dylib                   0x0000000107be3ad4 _dispatch_queue_override_invoke + 876
10  libdispatch.dylib                   0x0000000107bf1dc8 _dispatch_root_queue_drain + 372
11  libdispatch.dylib                   0x0000000107bf27ac _dispatch_worker_thread2 + 156
12  libsystem_pthread.dylib             0x00000002040ee1b4 _pthread_wqthread + 464
13  libsystem_pthread.dylib             0x00000002040f0cd4 start_wqthread + 4

**Comment by Gaozn** [comment]
EditScheme -> Run -> Main Thread Checker 取消勾选就行了。这个好像是ijk的问题

**Comment by Zeaa** [comment]
新版本已处理该警告问题
