### ISSUE TITLE
播放问题，卡在图中的地方一直不动连得wifi

### ISSUE THREAD

**Issue by grx123** [polyv/polyv-ios-vod-sdk#24]
![WechatIMG21645](https://user-images.githubusercontent.com/10874922/67551417-661fc500-f73b-11e9-9983-f5d4b6c7a2b6.jpeg)

**Comment by dengjunlun** [comment]
从提供的截图看并不能分析出是什么原因。目前sdk版本已经更新了，解决了很多问题，您可以使用最新的sdk版本试试看
