### ISSUE TITLE
bugly 统计crash

### ISSUE THREAD

**Issue by sun881122** [polyv/polyv-ios-vod-sdk#25]
ZeJiTiku | -[IJKMediaModule updateIdleTimer] (IJKMediaModule.m:0)
-- | --
11 ZeJiTiku | -[IJKFFMoviePlayerController setScreenOn:] (IJKFFMoviePlayerController.m:173)
12 ZeJiTiku | -[IJKFFMoviePlayerController shutdown] (IJKFFMoviePlayerController.m:575)
13 ZeJiTiku | -[PLVVodPlayerViewController stopPlayer] (PLVVodPlayerViewController.m:264)
14 ZeJiTiku | __57-[PLVVodPlayerViewController requestTokenWithCompletion:]_block_invoke (PLVVodPlayerViewController.m:1098)
15 ZeJiTiku | __56+[PLVVodNetworking requestVideoTokenWithVid:completion:]_block_invoke_2 (PLVVodNetworking.m:508)
16 ZeJiTiku | __49+[PLVVodNetworking requestDictionary:completion:]_block_invoke (PLVVodNetworking.m:0)
17 ZeJiTiku | __43+[PLVVodNetworking requestData:completion:]_block_invoke (PLVVodNetworking.m:62)

**Comment by dengjunlun** [comment]
目前我们已经对底层的ijkplayer做了私有化工作，最新版本也解决了很多问题。麻烦你升级一下sdk版本，若有问题请提供详细的crash信息。
