### ISSUE TITLE
iPad锁定横屏，不能小屏播放吗？

### ISSUE THREAD

**Issue by donotlazy** [polyv/polyv-ios-vod-sdk#26]
player?.addPlayer(onPlaceholderView: smallView, rootViewController: self.photoBrowser)
播放器添加到一个view上，在手机上显示正常，但是在iPad（只支持横屏）上直接就是全屏了。

**Comment by donotlazy** [comment]
/**
 添加播放器到占位视图上

 `placeholderView` 为竖屏时的占位视图，该视图需要先布局，播放器会参照该视图的布局而进行竖屏的布局。
 
 @param placeholderView 竖屏状态时的占位视图
 @param rootViewController 播放器所在页面的 UIViewController 对象
 */
- (void)addPlayerOnPlaceholderView:(UIView *)placeholderView rootViewController:(UIViewController *)rootViewController;

placeholderView 这个只能是竖屏状态时的占位视图吗？

**Comment by ali0201** [comment]
同问。。。貌似不能啵，请问你有木有解决了呢？

**Comment by donotlazy** [comment]
没解决呢

**Comment by alex521** [comment]
解决了吗

**Comment by dengjunlun** [comment]
/**
 添加播放器到占位视图上

 `placeholderView` 为竖屏时的占位视图，该视图需要先布局，播放器会参照该视图的布局而进行竖屏的布局。
 
 @param placeholderView 竖屏状态时的占位视图
 @param rootViewController 播放器所在页面的 UIViewController 对象
 */
- (void)addPlayerOnPlaceholderView:(UIView *)placeholderView rootViewController:(UIViewController *)rootViewController;


当设备竖屏的时候：播放器跟随placeholderView的大小。
当设备横屏的时候：播放器跟随rootViewController.view的大小。

所以ipad锁定横屏的时候，播放器是跟随rootViewController.view大小的，且自动是全屏的状态。

播放器皮肤层的代码是公开的，如果需要修改这部分逻辑，可在PolyvOpenSourceModule/Skin/PLVVodSkinPlayerController.m文件中修改。

[建议您在我们官网上联系技术支持，我们将会为您解答。](https://www.polyv.net/)
