### ISSUE TITLE
请问iPad中，如何使用AVPictureInPictureController？

### ISSUE THREAD

**Issue by ali0201** [polyv/polyv-ios-vod-sdk#27]
RT，貌似没在`PLVVodPlayerViewController`中找到`AVPlayer`，使用不了画中画功能。

请问如何解决呢？

**Comment by dengjunlun** [comment]
iOS的画中画功能是在AVPlayer基础上使用的，我们的播放器是基于ijkplayer开发的，并不是AVPlayer，所以暂时不支持画中画功能
