### ISSUE TITLE
SQLiteRepairKit cocoaPods更新不下来，有什么解决办法吗,更新了好几次

### ISSUE THREAD

**Issue by weiwei1991** [polyv/polyv-ios-vod-sdk#30]
<img width="594" alt="截屏2020-03-2711 42 12" src="https://user-images.githubusercontent.com/7012340/77719390-1b72e380-7020-11ea-8692-2d8fa0a3ec7a.png">
[!] Error installing SQLiteRepairKit
[!] /usr/bin/git clone https://github.com/Tencent/wcdb.git /var/folders/sx/kkc1nlyn02l8qpsr7wlnmj780000gn/T/d20200327-14712-17gedif --template= --single-branch --depth 1 --branch v1.0.8.2

Cloning into '/var/folders/sx/kkc1nlyn02l8qpsr7wlnmj780000gn/T/d20200327-14712-17gedif'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 60
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

有什么解决办法吗,更新了好几次

**Comment by YangYueFan** [comment]
+1

**Comment by xuepan12** [comment]
+1
