### ISSUE TITLE
找不到这个类

### ISSUE THREAD

**Issue by beautive** [polyv/polyv-ios-vod-sdk#31]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_IJKFFMoviePlayerController", referenced from:
      objc-class-ref in PLVVodSDK(PLVVodSettings.o)
      objc-class-ref in PLVVodSDK(PLVVodPlayerViewController.o)
      objc-class-ref in PLVVodSDK(PLVVodAdPlayerViewController.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lien006** [comment]
pod install 应该没有成功，相关依赖库没有正确安装
