### ISSUE TITLE
用户反馈App崩溃 , 通过bugly日志反馈 截图如下

### ISSUE THREAD

**Issue by Miles-Matheson** [polyv/polyv-ios-vod-sdk#32]
![image](https://user-images.githubusercontent.com/19796675/94357241-ac0ea700-00c9-11eb-8035-a87fa353af32.png)

**Comment by dengjunlun** [comment]
请问您是什么版本的点播sdk呢？vid麻烦提供一下

**Comment by dengjunlun** [comment]
您可以尝试使用我们最新的sdk试试看能否解决这个问题。目前通过截图暂时不能分析出什么问题，需要提供更多的信息。您可以通过官网联系我们，我们将会有专业的技术支持售后同事来对接这个问题。
