### ISSUE TITLE
点播SDK 目前不支持模拟器吗

### ISSUE THREAD

**Issue by Miles-Matheson** [polyv/polyv-ios-vod-sdk#33]
building for iOS Simulator, but linking in dylib built for iOS, file '/Users/xxx/Desktop/xxx/Pods/PolyvIJKPlayer/PolyvIJKMediaFramework.framework/PolyvIJKMediaFramework' for architecture arm64

**Comment by dengjunlun** [comment]
点播sdk是支持模拟器的x86_64架构的，请确保xcode的设置正确。
若是新版xcode，请设置build System为Legacy Build System

**Comment by dengjunlun** [comment]
点播sdk是支持模拟器的x86_64架构的，请确保xcode的设置正确。
若是新版xcode，请设置build System为Legacy Build System

**Comment by dengjunlun** [comment]
点播sdk是支持模拟器的x86_64架构的，请确保xcode的设置正确。
若是新版xcode，请设置build System为Legacy Build System
