### ISSUE TITLE
pod 安装包错

### ISSUE THREAD

**Issue by weiwei1991** [polyv/polyv-ios-vod-sdk#35]
<img width="1339" alt="截屏2020-11-09 下午5 59 54" src="https://user-images.githubusercontent.com/7012340/98526993-68f14780-22b5-11eb-9aa1-7e554180a89c.png">

**Comment by dengjunlun** [comment]
1、请检查您的网络环境是否正常访问github
2、更新本地pod仓库，pod repo update
