### ISSUE TITLE
使用的非加密视频播放，极少数人会出现黑屏有声音但是进度在走，重启设备或者app可以解决，同一个视频链接别的用户是没问题的。请问是怎么处理呢，问了别的同事好像是ijk打包可以处理这个问题

### ISSUE THREAD

**Issue by liuligithub** [polyv/polyv-ios-vod-sdk#36]

**Comment by liuligithub** [comment]
![image](https://user-images.githubusercontent.com/8730558/102845452-926ec880-4448-11eb-8862-5e9b93d63f0a.png)
删除图中的代码就可以解决

**Comment by dengjunlun** [comment]
是的，经过测试发现确实有这个问题，我们已经在点播2.14.1版本解决了。您可以升级sdk版本
