### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by iosLongFeng** [polyv/polyv-ios-vod-sdk#39]
In file included from /Users/ns/Desktop/projects/huaban/graves/ios/Pods/Headers/Public/Flipper-Folly/folly/portability/Event.h:24:
/Users/ns/Desktop/projects/huaban/graves/ios/Pods/Headers/Public/libevent/event.h:44:10: fatal error: 'event2/event-config.h' file not found

**Comment by dengjunlun** [comment]
看上去是Flipper工具sdk的报错，我们sdk中并没有使用Flipper。麻烦您检查一下您的项目中是否使用了Flipper，且Flipper是否正确完整集成
