### ISSUE TITLE
竖屏锁定，无法全屏

### ISSUE THREAD

**Issue by bobyang5437** [polyv/polyv-ios-vod-sdk#6]
[PLVVodPlayerViewController rotateOrientation:UIInterfaceOrientationLandscapeRight];方法无效

**Comment by lien006** [comment]
@bobyang5437 播放器是如何集成的？
关于横竖屏切换功能，可以参考中demo中：PLVVodPlayerSkin 类的switchScreen 方法。可以在demo中调测，熟悉相关功能
----------------------------
- (void)switchScreen {
	UIInterfaceOrientation interfaceOrientation = [UIApplication sharedApplication].statusBarOrientation;
	if (interfaceOrientation == UIInterfaceOrientationPortrait) {
		[PLVVodPlayerViewController rotateOrientation:UIInterfaceOrientationLandscapeRight];
	} else {
		[PLVVodPlayerViewController rotateOrientation:UIInterfaceOrientationPortrait];
	}
}

**Comment by miBliy** [comment]
不管用啊
