### ISSUE TITLE
服务器错误

### ISSUE THREAD

**Issue by xieguangqian1992** [polyv/polyv-ios-vod-sdk#8]
[PLVVODSDK_ERROR] 服务器错误，Error Domain=net.polyv.vod.sdk.ErrorDomain Code=20102 "服务器响应失败，状态码:404" UserInfo={NSURL=https://player.polyv.net/secure/57e976cbeae857c984dcb4c23c0e1640.json, NSLocalizedDescription=服务器响应失败，状态码:404}

**Comment by easefun** [comment]
vid不存在，你试试57e976cbeae857c984dcb4c23c0e1640_5

**Comment by xieguangqian1992** [comment]
好的
