### ISSUE TITLE
视频正在加载中退出页面后无法暂停播放器

### ISSUE THREAD

**Issue by wxzwork** [polyv/polyv-ios-vod-sdk#9]
进入播放页面，如果此时还在加载视频中，在viewWillDisappear中调有用暂停播放的方法，退出页面后视频加载完毕后仍会继续播放。有没有可以直接销毁播放器的方法呢，使得即使未加载完毕退出后也能停止播放器播放

**Comment by yuechenKMF** [comment]
会不会是代码写的有问题啊  还是退出要比较快一点

**Comment by lien006** [comment]
@wxzwork 是退出播放器页面，释放消失？还是暂离播放器页面，从播放器界面跳转进入下一个页面？如果是完全退出播放界面，释放控制器，demo中没复现你反馈的情况。也不需要在viewWillDisappear 调用pause 方法，播放器会自动释放掉。 你是在demo中，还是在自己的项目中出现这个问题的？

**Comment by wxzwork** [comment]
感谢俩位的解答，我是用demo的时候发现的，pop回上一个页面的时候视频还在加载的话，就可能出现这个问题，但是不好复现，我边也只复现出两次 @yuechenKMF @lien006

**Comment by yuechenKMF** [comment]
@wxzwork   好吧  我目前没有遇到  加载中 视频区域有一个loading  这个时候我退出 我们项目里是销毁了

**Comment by zeroskylian** [comment]
我也出现了

**Comment by dengjunlun** [comment]
请确保该页面没有内存泄漏的情况，播放器是会自动销毁的
